"use client";
import DarkenHexColor from "@/components/DarkenHexColor";
import { Friend, useFriend } from "@/context/friendContext";
import { cn } from "@/lib/utils";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";

const ScrollStyle = [
  "[&::-webkit-scrollbar]:w-2",
  "[&::-webkit-scrollbar-thumb]:rounded-full",
  "[&::-webkit-scrollbar-thumb]:bg-neutral-500",
];

export default function dmPage() {
  const path = usePathname().split("/");
  const { friends } = useFriend();
  const [friend, setFriend] = useState<Friend | undefined>(
    friends.friends.find((v) => v.username === path[3]),
  );
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!friend) {
      fetch(`${process.env.HOST_API_PUBLIC}/api/friend/${path[3]}`, {
        method: "GET",
        credentials: "include",
      })
        .then(async (res) => {
          const datas = await res.json();
          if (res.ok) {
            const data: Friend = datas.data;
            setFriend(data);
          }
        })
        .catch(() => {});
      setLoading(false);
    }
    setLoading(false);
  }, []);

  if (loading) return <div className="text-white">loading</div>;

  if (friend)
    return (
      <div className="flex min-w-0 flex-1 flex-col border-t border-neutral-700 bg-neutral-900 text-white">
        <div className="flex min-h-12 items-center border-b border-neutral-700 px-5">
          <img
            style={{
              backgroundColor: friend.picture.endsWith("default_picture.png")
                ? DarkenHexColor("#" + friend.id.slice(-6))
                : "",
            }}
            src={process.env.HOST_API_PUBLIC + friend.picture}
            alt=""
            className={cn(
              "size-6 rounded-full object-contain mr-4",
              friend.picture.endsWith("default_picture.png") && "p-[5px]",
            )}
          />
          <div>{friend.display_name}</div>
        </div>
        <div className={cn("mr-1 overflow-y-scroll", ScrollStyle)}>
          <div>tes</div>jkk
          <div>tes \n \n asdf</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>tes</div>
          <div>end</div>
        </div>
        <div className="min-h-12"></div>
      </div>
    );
  return <div className="text-white">takde</div>;
}
