import { useEffect, useRef } from "react";

export default function ListChat() {
  const boxRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const el = boxRef.current;
    if (!el) return;
    el.scrollTop = el.scrollHeight;
  }, []);
  return (
    <div ref={boxRef} className="flex-1 overflow-y-scroll bg-neutral-900">
      <div>old</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>atestsetsetset</div>
      <div>new</div>
      <div>end</div>
    </div>
  );
}
